#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertUrl
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bfinance")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertvndd_category2(vndd_category2 instance);
    partial void Updatevndd_category2(vndd_category2 instance);
    partial void Deletevndd_category2(vndd_category2 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConvertUrl.Properties.Settings.Default.bfinanceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vndd_category2> vndd_category2s
		{
			get
			{
				return this.GetTable<vndd_category2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vndd_category")]
	public partial class vndd_category2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _code;
		
		private string _name;
		
		private string _note;
		
		private string _filepreview;
		
		private System.Nullable<int> _cid;
		
		private System.Nullable<int> _orderd;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<int> _markas;
		
		private string _iconex;
		
		private System.Nullable<System.DateTime> _timeupdate;
		
		private string _username;
		
		private System.Nullable<int> _pis;
		
		private System.Nullable<int> _pid;
		
		private System.Nullable<int> _depth;
		
		private string _forsearch;
		
		private string _url;
		
		private System.Nullable<int> _customizeid;
		
		private string _alias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnfilepreviewChanging(string value);
    partial void OnfilepreviewChanged();
    partial void OncidChanging(System.Nullable<int> value);
    partial void OncidChanged();
    partial void OnorderdChanging(System.Nullable<int> value);
    partial void OnorderdChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void OnmarkasChanging(System.Nullable<int> value);
    partial void OnmarkasChanged();
    partial void OniconexChanging(string value);
    partial void OniconexChanged();
    partial void OntimeupdateChanging(System.Nullable<System.DateTime> value);
    partial void OntimeupdateChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpisChanging(System.Nullable<int> value);
    partial void OnpisChanged();
    partial void OnpidChanging(System.Nullable<int> value);
    partial void OnpidChanged();
    partial void OndepthChanging(System.Nullable<int> value);
    partial void OndepthChanged();
    partial void OnforsearchChanging(string value);
    partial void OnforsearchChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OncustomizeidChanging(System.Nullable<int> value);
    partial void OncustomizeidChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    #endregion
		
		public vndd_category2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(MAX)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filepreview", DbType="NVarChar(255)")]
		public string filepreview
		{
			get
			{
				return this._filepreview;
			}
			set
			{
				if ((this._filepreview != value))
				{
					this.OnfilepreviewChanging(value);
					this.SendPropertyChanging();
					this._filepreview = value;
					this.SendPropertyChanged("filepreview");
					this.OnfilepreviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int")]
		public System.Nullable<int> cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orderd", DbType="Int")]
		public System.Nullable<int> orderd
		{
			get
			{
				return this._orderd;
			}
			set
			{
				if ((this._orderd != value))
				{
					this.OnorderdChanging(value);
					this.SendPropertyChanging();
					this._orderd = value;
					this.SendPropertyChanged("orderd");
					this.OnorderdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markas", DbType="Int")]
		public System.Nullable<int> markas
		{
			get
			{
				return this._markas;
			}
			set
			{
				if ((this._markas != value))
				{
					this.OnmarkasChanging(value);
					this.SendPropertyChanging();
					this._markas = value;
					this.SendPropertyChanged("markas");
					this.OnmarkasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iconex", DbType="NVarChar(255)")]
		public string iconex
		{
			get
			{
				return this._iconex;
			}
			set
			{
				if ((this._iconex != value))
				{
					this.OniconexChanging(value);
					this.SendPropertyChanging();
					this._iconex = value;
					this.SendPropertyChanged("iconex");
					this.OniconexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timeupdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> timeupdate
		{
			get
			{
				return this._timeupdate;
			}
			set
			{
				if ((this._timeupdate != value))
				{
					this.OntimeupdateChanging(value);
					this.SendPropertyChanging();
					this._timeupdate = value;
					this.SendPropertyChanged("timeupdate");
					this.OntimeupdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pis", DbType="Int")]
		public System.Nullable<int> pis
		{
			get
			{
				return this._pis;
			}
			set
			{
				if ((this._pis != value))
				{
					this.OnpisChanging(value);
					this.SendPropertyChanging();
					this._pis = value;
					this.SendPropertyChanged("pis");
					this.OnpisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pid", DbType="Int")]
		public System.Nullable<int> pid
		{
			get
			{
				return this._pid;
			}
			set
			{
				if ((this._pid != value))
				{
					this.OnpidChanging(value);
					this.SendPropertyChanging();
					this._pid = value;
					this.SendPropertyChanged("pid");
					this.OnpidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depth", DbType="Int")]
		public System.Nullable<int> depth
		{
			get
			{
				return this._depth;
			}
			set
			{
				if ((this._depth != value))
				{
					this.OndepthChanging(value);
					this.SendPropertyChanging();
					this._depth = value;
					this.SendPropertyChanged("depth");
					this.OndepthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forsearch", DbType="NVarChar(MAX)")]
		public string forsearch
		{
			get
			{
				return this._forsearch;
			}
			set
			{
				if ((this._forsearch != value))
				{
					this.OnforsearchChanging(value);
					this.SendPropertyChanging();
					this._forsearch = value;
					this.SendPropertyChanged("forsearch");
					this.OnforsearchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(255)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customizeid", DbType="Int")]
		public System.Nullable<int> customizeid
		{
			get
			{
				return this._customizeid;
			}
			set
			{
				if ((this._customizeid != value))
				{
					this.OncustomizeidChanging(value);
					this.SendPropertyChanging();
					this._customizeid = value;
					this.SendPropertyChanged("customizeid");
					this.OncustomizeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="NVarChar(500)")]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
